Fix bug which is breaking production builds
Previously got "Uncaught TypeError: ka.format is not a function"
so that `ka.format` referred to `gstring/format`.
No idea why and no time to investigate. 🤷‍♂️